name: Auto Update README Projects

on:
  schedule:
    - cron: '0 0 * * *' # Chạy tự động mỗi ngày vào lúc 00:00
  workflow_dispatch:      # Cho phép bạn bấm nút chạy thủ công (Manual trigger)
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: pubs/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Update Script
        run: python update_projects.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add README.md
          git commit -m "chore: 🌸 auto-update featured projects" || exit 0
          git push